# 注释版本
server:
  port: 18084
spring:
  application:
    name: api-gateway # 应用名
  cloud:
    gateway:
      routes:
        # 用户所有以/user开始的请求，都给http://localhost:18081服务处理
        #id唯一标识，可自定义 , 随便写，可以写小红，小花都行
        - id: user-service-route
#          #路由的服务地址
#          uri: http://localhost:18081
#          # 路由拦截的地址配置（断言）
#          # /user/**所有以/user开始的请求都将被路由到uri指定的服务地址，
#          # 将该请求交给uri指定的服务处理，比如请求：http://localhost:18084/user/find/2会把请求交给http://localhost:18081/user/find/2处理
          #路由的服务地址
          #uri: http://localhost:18081 请求负载均衡算法Load Balance
          #lb协议表示从Eureka注册中心获取服务请求地址
          #user-provider访问的服务名称。
          #路由地址如果通过lb协议加服务名称时，会自动使用负载均衡访问对应服务
          uri: lb://user-provider
          # 路由拦截的地址配置（断言）
          predicates:
            - Path=/user/**
# Eureka服务中心配置
eureka:
  client:
    service-url:
      # 注册Eureka Server集群
      defaultZone: http://127.0.0.1:7001/eureka
