server:
  port: 18081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  application:
    name: user-provider #服务的名字,不同的应用，名字不同，如果是集群，名字需要相同

# 修改服务地址轮询策略，默认是轮询，配置之后变随机
user-provider:
  ribbon:
  #轮询
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#    ConnectTimeout: 1000 # 连接超时时间 没有连接上
#    ReadTimeout: 2000 # 数据读取超时时间 连接上了，连上之后开始计时，但读取数据需要花费很长时间
#    MaxAutoRetries: 1 # 最大重试次数(第一个服务)在第一次连接超时之后，在重新连接一次
#    MaxAutoRetriesNextServer: 0 # 最大重试下一个服务次数(集群的情况才会用到)
#    OkToRetryOnAllOperations: false # 是否所有操作都进行重试

#指定eureka服务地址
eureka:
  client:
    service-url:
      # EurekaServer的地址
      defaultZone: http://localhost:7001/eureka
    # 每隔30秒获取服务中心列表，（只读备份）
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    #租约到期，服务时效时间，默认值90秒
    lease-expiration-duration-in-seconds: 150
    #租约续约间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 30