server:
  port: 7001    #端口号
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中作为服务的id标识（serviceId）
eureka:
  client:
    register-with-eureka: false   #是否将自己注册到Eureka中
    fetch-registry: false   #是否从eureka中获取服务信息
    service-url:
      defaultZone: http://localhost:7001/eureka # EurekaServer的地址
  server:
    # 对无效的服务进行剔除操作，单位是毫秒
    eviction-interval-timer-in-ms: 5000
    # 关闭自我保护模式（缺省为打开）
    enable-self-preservation: false

